# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
 
pool:
  vmImage: windows-latest
  #env:
    #PAYLOAD: ${{toJSON(github.event.client_payload)}}
steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      targetPath: '$(Pipeline.Workspace)'
  - script: |
      curl --help
      echo "Hello World"
      node --version
      node hello.js
    displayName: 'Dowmload index.js from GitHub'
   
      
    
  

  
    
      

  