name: InfraProvisioningPipeline
on: 
  repository_dispatch:
    types: webhook

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: hello
        run: echo "Hello World"
        shell: bash
      
      
