name: InfraProvisioningPipeline
on: 
  repository_dispatch:
    types: webhook

jobs:
  test:
    runs-on: windows-latest
    env: 
      PAYLOAD: ${{toJSON(github.event.client_payload)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: hello
        run: echo "Hello World"
        shell: bash
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
      - name: node version
        run: node --version
      - name: run js file
        run: node index.js
  notify_service_now:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Notify ServiceNow on failure
        if: failure()
        run: |
          curl -X POST -H "Content-Type": application/json -H
          "Authorization: Bearer ${{secrets.SERVICE_NOW_API_KEY}}" -d 
          '{
              "u_task_number":"SCTASK0010089",
              "u_state":"Closed Incomplete",
              "u_stage":"Fulfillment",
              "u_status":"Communication Error"}'
              https://dev85238.service-now.com/api/now/import/u_status_api
      
