name: InfraProvisioningPipeline
on: 
  repository_dispatch:
    types: webhook

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: hello
        run: echo "Hello World"
        shell: bash
      - name: payload processing
        run: | 
          echo ":: set-env
          name=PAYLOAD::${{toJSON(github.event.client_payload)}}
          "

      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
      - name: node version
        run: node --version
      - name: run js file
        run: node index.js
      
      
      
