name: Test Action
on:
  workflow_dispatch:
  repository_dispatch:
    types: [dependency_update]
      
jobs:
  hello:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: hello
        run: echo "Hello world"
        shell: bash
