name: Test Action
on:
  workflow_dispatch:
  repository_dispatch:
    types: 
      - webhook
      
jobs:
  hello:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: hello
        run: echo "hello world!"
        shell: bash
      - name: Process Webhook
        id: webhook 
        run: echo 'Payload - ${{toJSON(github.event)}}'
