name: Test Action
on:
  workflow_dispatch:
  repository_dispatch:
    type:
      - webhook
jobs:
  hello:
    runs-on: ubantu-latest
    steps:
      - name: hello
        run: echo "Hello world"
        shell: bash
